name: 'idx_stock'
version: '1.0.0'
config-version: 2

profile: 'idx_stock'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  idx_stock:
    staging:
      +materialized: view
      +schema: staging
    marts:
      core:
        +materialized: table
        +schema: core
      analytics:
        +materialized: table
        +schema: analytics